### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by Chklang** [ifedu/generator-speedseed#1]
Hi

I've tried to initiate a project with your generator but i've an error : 

> $ yo speedseed
> C:\Program Files\nodejs\node_modules\generator-speedseed\generators\app\index.js:3
> const config = require('../_config.js')
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.defineProperty.get [as speedseed:app](C:Program Filesnodejsnode_modulesyonode_modulesyeoman-environmentlibstore.js:40:23)
>     at Store.get (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
>     at Environment.get (C:\Program Files\nodejs\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:260:16)

Regards

**Comment by ifedu** [comment]
Hello!

I hope to help, what NodeJS version you use?

Only works in >4.0.0
