### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by StefanKoenen** [ifedu/generator-speedseed#3]
Hi,
I'm trying to add a test to my project, but it's never called. Already working on it for a few hours, but i'm not sure whats wrong.

```
> 02 07 2016 17:12:57.610:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
> 02 07 2016 17:12:57.616:INFO [launcher]: Starting browser PhantomJS
> 02 07 2016 17:12:59.410:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket /#Y5iEk7GWp6GB1YMtAAAA with id 91978388
> PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
> PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
```

**Comment by ifedu** [comment]
Hi!,

The version was buged in the test, you should update to version 0.16.0 or higher

New version Require Node6.0.0

If install in a new project it should work, but if you update your current project, you should change .core-config.js, the property test to:
"test": {
        "exclude": [],
        "files": [
            "./-build/js/**/*.js",
            "./-build/components/**/_.js",
            "./-tmp/__/_.spec.js"
        ],
        "preprocessors": {}
    }

The test must be called *.spec.js, In the next version will be better documented in the README, and the template multi-tic-tac-toe come with test example
