### ISSUE TITLE
Speedseed doesnt run

### ISSUE THREAD

**Issue by daddydrac** [ifedu/generator-speedseed#39]
not sure why, but it doesnt run or build into my folder. only at the global level.

**Comment by ifedu** [comment]
Hello!

It would need more information to know well the problem, so tell me, could be due a Yeoman.

With this structure:

```
> projects
>     projectA
>         .yo-rc.json
>     projectB
>     .yo-rc.json
```

If you run speedseed start on projects/projectA will work than expected, while in projects/projectB look projects/.yo-rc.json

Sorry for the delay, I hope that you serve, greetings.
